feat: 배달관련 기능 개발
puleugo/IJS pull request #3
Opened 2023-05-18 04:15 UTC by haroya01

2023-05-18 04:18 UTC, puleugo requested changes
리뷰 시연

2023-05-18 04:18 UTC, puleugo commented on package.json
> +    "rxjs": "^7.8.1",
요거 수정할 필요가 없습니다.
`yarn install rxjs@7.5.6`을 통해서 버전을 롤백해주세요.

2023-05-18 04:19 UTC, puleugo commented on package.json
> +    "rxjs": "^7.8.1",
`yarn add rxjs@7.5.6`로 정정합니다.

2023-05-18 04:21 UTC, haroya01 commented on package.json
> +    "rxjs": "^7.8.1",
롤백했습니다~ [8144815](https://github.com/puleugo/IJS/pull/3/commits/8144815dd1f6e0bf5a327c3b28d8ee1cf7e715ed)

2023-05-18 07:26 UTC, puleugo commented on src/app/app.module.ts
> +
지금 ESLINT 적용이 안되어있나보네용.
다음부터는 git push 전에 eslint& prettier을 적용하시고 푸시해주세용

2023-05-18 07:32 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
>  //TODO: 구현
구현이 완료되었다면, TODO 삭제 해주세요.
IDE에서 추후에 구현해야할 내용들을 `//TODO: 작업 내용`을 주석으로 달면 할일들을 목록으로 조회할 수 있어요.
VSC에서도 Name: [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) 라는 확장 프로그램으로 관리할 수 있습니다~

<img width="1912" alt="스크린샷 2023-05-18 오후 4 28 30" src="https://github.com/puleugo/IJS/assets/75980875/ad02e8d3-59c3-48c8-ba0e-5baa3bdf417b">

2023-05-18 07:34 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
> +      (deliveryService) => new DeliveryPreviewResponse(deliveryService),
여기 오타있네요. 수정해주세용.
deliveryService라는 이름의 변수를 생성해서 위 deliveryService 변수와 충돌날 수 있습니다.
```suggestion
    return deliveries.map(
      (delivery) => new DeliveryPreviewResponse(delivery),
```

2023-05-18 07:34 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
> +import { dirxml } from 'console';
사용하지 않는 라이브러리네용.
```suggestion
```

2023-05-18 07:37 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
> +    }
컨트롤러 레벨에서는 에러를 던지는 것을 권장드리지 않아요.
`getDeliveryById`함수의 서비스 레벨에서 `delivery`를 찾지 못했을 때 커스터마이징한 에러를 던지는 것을 추천드립니다.
```suggestion
```

2023-05-18 07:38 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
> +    deliveryData: {
이 createRequest 바디의 값을 클래스로 생성해보시죠.
`command` 파일이랑 `dto` 파일을 참고하시고 한번 시도해보세용.

2023-05-18 07:39 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
> +      show: boolean;
이 createRequest 바디의 값을 클래스로 생성해보시죠.
command 파일이랑 dto 파일을 참고하시고 한번 시도해보세용.

2023-05-18 07:40 UTC, puleugo commented on src/app/delivery/delivery.controller.ts
>    }
입장한 delivery를 반환해주는 것을 권장합니다. 프론트엔드 입장에서는 입장을 성공했는지 확인하고 싶을거에요.

2023-05-18 07:41 UTC, puleugo commented on src/app/delivery/delivery.service.ts
> +    // 데이터
요런 주석은 없애는걸 권장드려요.

2023-05-18 07:42 UTC, puleugo commented on src/app/delivery/delivery.service.ts
> +    });
찾는데 성공한 유저가 이미 해당 delivery에 입장해 있을 때도 예외처리해야할 듯합니다.

2023-05-18 07:43 UTC, puleugo commented on src/app/delivery/dto/delivery-profile.response.ts
> +  }: any) {
현재 any타입에서 프로퍼티를 제공받고 있지만 제공받을 타입을 지정해보세요.

2023-05-18 07:44 UTC, puleugo requested changes
1차 코드리뷰

2023-05-18 12:38 UTC, haroya01 commented on src/app/delivery/delivery.controller.ts
>  //TODO: 구현
bbf6095f4db5c5ee2f8b8164b7dfd02f07915a1a
수정했습니다.

2023-05-18 13:03 UTC, haroya01 commented on src/app/delivery/delivery.controller.ts
> +import { dirxml } from 'console';
ed602bb188ff6a1e9ce87fcc655cfd0626695520
dirxml 라이브러리 제거했습니다

2023-05-18 13:32 UTC, haroya01 commented on src/app/delivery/delivery.controller.ts
> +    }
07ae35571001c6e52d77ccc7c39e37b6c2e4b2e8
컨트롤러 쪽 에러메세지를 삭제하고 서비스쪽에 오류출력코드를 추가했습니다.

2023-05-18 13:43 UTC, haroya01 commented on src/app/delivery/delivery.service.ts
> +    });
88022f8f307d7fa8cc4cac1bd15bef1218647f83 
delivery에 이미 입장해있을 경우의 예외처리를 추가했습니다.

2023-05-18 14:12 UTC, haroya01 commented on src/app/delivery/delivery.controller.ts
>    }
0c283e188bfa2b296686c59165ac40863932197c
입장한 delivery를 반환하는 기능을 추가했습니다.

2023-05-20 09:09 UTC, haroya01 commented on src/app/delivery/delivery.controller.ts
> +      show: boolean;
c316a7c2831d46164da9aa950ce917bea57ec514
DeliveryData 타입 추가했습니다.

2023-05-20 10:58 UTC, haroya01 commented on src/app/app.module.ts
> +
7565346ce3b5cde0cf864f32d7f4a8bd33d3346c 
적용했습니다.

2023-05-20 11:12 UTC, haroya01 commented on src/app/delivery/dto/delivery-profile.response.ts
> +  }: any) {
05099717f6b2c0ec37f6b532c0f1037500f37a82 
타입을 지정한뒤 그에 맞춰서 
entitiy에 deliveryUrl을 추가했습니다.

2023-05-31 09:25 UTC, merged